// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.HealthStatusResponse"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.ReadinessStatusResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/http.ReadinessStatusResponse"
                        }
                    }
                }
            }
        },
        "/v1/admin/audit-logs": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Audit"
                ],
                "summary": "List tenant audit logs",
                "parameters": [
                    {
                        "maximum": 200,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Maximum number of logs to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Tenant API key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Development/local user email",
                        "name": "X-User-Email",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Display name",
                        "name": "X-User-Name",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Set to true for platform admin requests",
                        "name": "X-Platform-Admin",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.AuditLogListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/admin/instances": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "List all deployed OpenClaw instances across all tenants",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Admin email",
                        "name": "X-User-Email",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Set to true",
                        "name": "X-Platform-Admin",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.AdminInstanceListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/admin/openclaw/deploy": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Deploy OpenClaw for a target user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Admin email",
                        "name": "X-User-Email",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Set to true",
                        "name": "X-Platform-Admin",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "OpenClaw deployment payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.adminDeployOpenClawInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http.adminDeployOpenClawResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/admin/summary": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get platform summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant API key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Development/local user email",
                        "name": "X-User-Email",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Display name",
                        "name": "X-User-Name",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Set to true for platform admin requests",
                        "name": "X-Platform-Admin",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AdminSummary"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/admin/users": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Provision a user as platform admin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Admin email",
                        "name": "X-User-Email",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Set to true",
                        "name": "X-Platform-Admin",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "User provision payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.adminCreateUserInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Actor"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/api-keys": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API Keys"
                ],
                "summary": "List tenant API keys",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant API key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Development/local user email",
                        "name": "X-User-Email",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Display name",
                        "name": "X-User-Name",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Set to true for platform admin requests",
                        "name": "X-Platform-Admin",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.APIKeyListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API Keys"
                ],
                "summary": "Create a tenant API key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant API key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Development/local user email",
                        "name": "X-User-Email",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Display name",
                        "name": "X-User-Name",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Set to true for platform admin requests",
                        "name": "X-Platform-Admin",
                        "in": "header"
                    },
                    {
                        "description": "API key create request",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.APIKeyCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http.APIKeyCreateResultResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/api-keys/{keyID}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API Keys"
                ],
                "summary": "Revoke an API key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API key ID",
                        "name": "keyID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant API key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Development/local user email",
                        "name": "X-User-Email",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Display name",
                        "name": "X-User-Name",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Set to true for platform admin requests",
                        "name": "X-Platform-Admin",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/apps": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Apps"
                ],
                "summary": "List apps for the current tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant API key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Development/local user email",
                        "name": "X-User-Email",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Display name",
                        "name": "X-User-Name",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Set to true for platform admin requests",
                        "name": "X-Platform-Admin",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.AppListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Apps"
                ],
                "summary": "Create an app",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant API key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Development/local user email",
                        "name": "X-User-Email",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Display name",
                        "name": "X-User-Name",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Set to true for platform admin requests",
                        "name": "X-Platform-Admin",
                        "in": "header"
                    },
                    {
                        "description": "App definition",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.CreateAppInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.App"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/apps/{appID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Apps"
                ],
                "summary": "Get an app",
                "parameters": [
                    {
                        "type": "string",
                        "description": "App ID",
                        "name": "appID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant API key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Development/local user email",
                        "name": "X-User-Email",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Display name",
                        "name": "X-User-Name",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Set to true for platform admin requests",
                        "name": "X-Platform-Admin",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.App"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Apps"
                ],
                "summary": "Update an app",
                "parameters": [
                    {
                        "type": "string",
                        "description": "App ID",
                        "name": "appID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant API key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Development/local user email",
                        "name": "X-User-Email",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Display name",
                        "name": "X-User-Name",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Set to true for platform admin requests",
                        "name": "X-Platform-Admin",
                        "in": "header"
                    },
                    {
                        "description": "Partial app update",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.UpdateAppInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.App"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/apps/{appID}/deployments": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployments"
                ],
                "summary": "List deployments for an app",
                "parameters": [
                    {
                        "type": "string",
                        "description": "App ID",
                        "name": "appID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant API key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Development/local user email",
                        "name": "X-User-Email",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Display name",
                        "name": "X-User-Name",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Set to true for platform admin requests",
                        "name": "X-Platform-Admin",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.DeploymentListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployments"
                ],
                "summary": "Create a deployment for an app",
                "parameters": [
                    {
                        "type": "string",
                        "description": "App ID",
                        "name": "appID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant API key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Development/local user email",
                        "name": "X-User-Email",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Display name",
                        "name": "X-User-Name",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Set to true for platform admin requests",
                        "name": "X-Platform-Admin",
                        "in": "header"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Deployment"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/medium/callback": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Handle Medium OAuth callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OAuth callback code",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Redirect URI",
                        "name": "redirect_uri",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Actor"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/medium/login": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get Medium OAuth login URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Redirect URI",
                        "name": "redirect_uri",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.LoginURLResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/providers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "List supported auth providers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.AuthProvidersResponse"
                        }
                    }
                }
            }
        },
        "/v1/deployments/{deploymentID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployments"
                ],
                "summary": "Get a deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deployment ID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant API key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Development/local user email",
                        "name": "X-User-Email",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Display name",
                        "name": "X-User-Name",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Set to true for platform admin requests",
                        "name": "X-Platform-Admin",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Deployment"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/deployments/{deploymentID}/cancel": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployments"
                ],
                "summary": "Cancel a queued or provisioning deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deployment ID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant API key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Development/local user email",
                        "name": "X-User-Email",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Display name",
                        "name": "X-User-Name",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Set to true for platform admin requests",
                        "name": "X-Platform-Admin",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Deployment"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/deployments/{deploymentID}/delete": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployments"
                ],
                "summary": "Queue deployment deletion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deployment ID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant API key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Development/local user email",
                        "name": "X-User-Email",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Display name",
                        "name": "X-User-Name",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Set to true for platform admin requests",
                        "name": "X-Platform-Admin",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Deployment"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/deployments/{deploymentID}/events": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployments"
                ],
                "summary": "List deployment events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deployment ID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant API key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Development/local user email",
                        "name": "X-User-Email",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Display name",
                        "name": "X-User-Name",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Set to true for platform admin requests",
                        "name": "X-Platform-Admin",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.DeploymentEventListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/deployments/{deploymentID}/retry": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployments"
                ],
                "summary": "Retry a failed or cancelled deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deployment ID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant API key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Development/local user email",
                        "name": "X-User-Email",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Display name",
                        "name": "X-User-Name",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Set to true for platform admin requests",
                        "name": "X-Platform-Admin",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Deployment"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Return the current actor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant API key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Development/local user email",
                        "name": "X-User-Email",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Display name",
                        "name": "X-User-Name",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Set to true for platform admin requests",
                        "name": "X-Platform-Admin",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Actor"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.APIKey": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "key_prefix": {
                    "type": "string"
                },
                "last_used_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "revoked_at": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "domain.Actor": {
            "type": "object",
            "properties": {
                "api_key_id": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "is_platform_admin": {
                    "type": "boolean"
                },
                "role": {
                    "$ref": "#/definitions/domain.Role"
                },
                "tenant_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "domain.AdminInstance": {
            "type": "object",
            "properties": {
                "app": {
                    "$ref": "#/definitions/domain.App"
                },
                "deployment": {
                    "$ref": "#/definitions/domain.Deployment"
                },
                "user_email": {
                    "type": "string"
                }
            }
        },
        "domain.AdminSummary": {
            "type": "object",
            "properties": {
                "apps": {
                    "type": "integer"
                },
                "deployments": {
                    "type": "integer"
                },
                "failed_deployments": {
                    "type": "integer"
                },
                "repository_driver": {
                    "type": "string"
                },
                "tenants": {
                    "type": "integer"
                },
                "users": {
                    "type": "integer"
                }
            }
        },
        "domain.App": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/domain.AppConfig"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "current_deployment_id": {
                    "type": "string"
                },
                "desired_state": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.AppConfig": {
            "type": "object",
            "properties": {
                "cpu_limit": {
                    "type": "string"
                },
                "cpu_request": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "env": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "image": {
                    "type": "string"
                },
                "memory_limit": {
                    "type": "string"
                },
                "memory_request": {
                    "type": "string"
                },
                "openclaw": {
                    "$ref": "#/definitions/domain.OpenClawConfig"
                },
                "port": {
                    "type": "integer"
                },
                "public": {
                    "type": "boolean"
                },
                "replicas": {
                    "type": "integer"
                },
                "service_account_name": {
                    "type": "string"
                }
            }
        },
        "domain.AuditLog": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "actor_api_key_id": {
                    "type": "string"
                },
                "actor_user_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "resource_id": {
                    "type": "string"
                },
                "resource_type": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                }
            }
        },
        "domain.BackendRef": {
            "type": "object",
            "properties": {
                "deployment": {
                    "type": "string"
                },
                "ingress_name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "service": {
                    "type": "string"
                }
            }
        },
        "domain.Deployment": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "backend": {
                    "type": "string"
                },
                "backend_ref": {
                    "$ref": "#/definitions/domain.BackendRef"
                },
                "config_snapshot": {
                    "$ref": "#/definitions/domain.AppConfig"
                },
                "created_at": {
                    "type": "string"
                },
                "finished_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_ref": {
                    "type": "string"
                },
                "requested_by": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.DeploymentStatus"
                },
                "status_reason": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "domain.DeploymentEvent": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deployment_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.DeploymentStatus": {
            "type": "string",
            "enum": [
                "requested",
                "queued",
                "provisioning",
                "running",
                "failed",
                "cancelled",
                "deleting",
                "deleted"
            ],
            "x-enum-varnames": [
                "DeploymentStatusRequested",
                "DeploymentStatusQueued",
                "DeploymentStatusProvisioning",
                "DeploymentStatusRunning",
                "DeploymentStatusFailed",
                "DeploymentStatusCancelled",
                "DeploymentStatusDeleting",
                "DeploymentStatusDeleted"
            ]
        },
        "domain.OpenClawConfig": {
            "type": "object",
            "properties": {
                "agents_markdown": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "existing_secret_name": {
                    "type": "string"
                },
                "extra_env": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "gateway_bind_address": {
                    "type": "string"
                },
                "gateway_port": {
                    "type": "integer"
                },
                "gateway_token": {
                    "type": "string"
                },
                "provider_api_keys": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "settings_json": {
                    "type": "string"
                },
                "workspace_storage": {
                    "type": "string"
                }
            }
        },
        "domain.Role": {
            "type": "string",
            "enum": [
                "owner",
                "admin",
                "member"
            ],
            "x-enum-varnames": [
                "RoleOwner",
                "RoleAdmin",
                "RoleMember"
            ]
        },
        "http.APIKeyCreateRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "http.APIKeyCreateResultResponse": {
            "type": "object",
            "properties": {
                "key": {
                    "$ref": "#/definitions/domain.APIKey"
                },
                "secret": {
                    "type": "string"
                }
            }
        },
        "http.APIKeyListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.APIKey"
                    }
                }
            }
        },
        "http.AdminInstanceListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.AdminInstance"
                    }
                }
            }
        },
        "http.AppListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.App"
                    }
                }
            }
        },
        "http.AuditLogListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.AuditLog"
                    }
                }
            }
        },
        "http.AuthProvidersResponse": {
            "type": "object",
            "properties": {
                "providers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "http.DeploymentEventListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.DeploymentEvent"
                    }
                }
            }
        },
        "http.DeploymentListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Deployment"
                    }
                }
            }
        },
        "http.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "http.HealthStatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "http.LoginURLResponse": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "http.ReadinessStatusResponse": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        },
        "http.adminCreateUserInput": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "http.adminDeployOpenClawInput": {
            "type": "object",
            "properties": {
                "agents_markdown": {
                    "type": "string"
                },
                "app_name": {
                    "type": "string"
                },
                "app_slug": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "existing_secret_name": {
                    "type": "string"
                },
                "extra_env": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "gateway_bind_address": {
                    "type": "string"
                },
                "gateway_port": {
                    "type": "integer"
                },
                "gateway_token": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "provider_api_keys": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "public": {
                    "type": "boolean"
                },
                "replicas": {
                    "type": "integer"
                },
                "settings_json": {
                    "type": "string"
                },
                "user_email": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                },
                "workspace_storage": {
                    "type": "string"
                }
            }
        },
        "http.adminDeployOpenClawResponse": {
            "type": "object",
            "properties": {
                "app": {
                    "$ref": "#/definitions/domain.App"
                },
                "deployment": {
                    "$ref": "#/definitions/domain.Deployment"
                },
                "used_existing_app": {
                    "type": "boolean"
                },
                "user": {
                    "$ref": "#/definitions/domain.Actor"
                }
            }
        },
        "services.CreateAppInput": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/domain.AppConfig"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "services.UpdateAppInput": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/domain.AppConfig"
                },
                "desired_state": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "APIKeyHeader": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        },
        "UserEmailHeader": {
            "type": "apiKey",
            "name": "X-User-Email",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Clawflux API",
	Description:      "Code-first Swagger docs for the current Clawflux HTTP API.\n\nAuth behavior:\n- Most /v1 endpoints accept either X-API-Key or X-User-Email.\n- DEVELOPMENT_AUTH=true allows unauthenticated local requests as developer@local.\n- Platform admin endpoints additionally require X-Platform-Admin: true.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
